### ISSUE TITLE
[FEATURE] Hacktoberfest label

### ISSUE THREAD

**Issue by Nakamcode** [global-hacktoberfest22/educate-blog#2]
**Here is a list of user-friendly labels you can add**

- hacktoberfest
- good first issue
- scope/frontend
- scope/backend
- status/accepted
- status/decline
- documentation
- help wanted**

**Comment by mdnazisharman2803** [comment]
Nice idea. I liked the scope version of label 🤘

**Comment by chiragchandnani10** [comment]
Can you add the task which we have to perform? Thanks!

**Comment by mdnazisharman2803** [comment]
> Can you add the task which we have to perform? Thanks!

This is not the valid issue.. It's just a suggestion. Our design is about to ready and then issues will be created. Like Login, sign up page. Stay tuned. Thanks
